version: "3.8"

services:
  traefik:
    image: traefik:2.10.4
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - traefik-acme-data:/acme
      - ./traefik.yml:/etc/traefik/traefik.yml
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik-dashboard.entrypoints=websecure
      - traefik.http.routers.traefik-dashboard.rule=Host(`traefik.ulexxander.work`)
      - traefik.http.routers.traefik-dashboard.service=api@internal
      - traefik.http.routers.traefik-dashboard.middlewares=auth-errors,auth-proxy

  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.5.0
    command:
      - --http-address=:4180
      - --reverse-proxy
      - --cookie-secure=false
      - --email-domain=*
      - --provider=gitlab
      - --oidc-issuer-url=https://gitlab.com
      - --pass-user-headers
      - --set-xauthrequest
    # Must contain:
    # OAUTH2_PROXY_CLIENT_ID
    # OAUTH2_PROXY_CLIENT_SECRET
    # OAUTH2_PROXY_COOKIE_SECRET
    env_file: oauth2-proxy.env
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.oauth2-proxy.entrypoints=websecure
      - traefik.http.routers.oauth2-proxy.rule=HostRegexp(`{wildcard:[a-z]+}.ulexxander.work`) && PathPrefix(`/oauth2`)
      - traefik.http.services.oauth2-proxy.loadbalancer.server.port=4180
      - traefik.http.middlewares.auth-proxy.forwardauth.address=http://oauth2-proxy:4180/oauth2/auth
      - traefik.http.middlewares.auth-proxy.forwardauth.trustForwardHeader=true
      - traefik.http.middlewares.auth-proxy.forwardauth.authResponseHeaders=X-Auth-Request-User,X-Auth-Request-Groups,X-Auth-Request-Email
      - traefik.http.middlewares.auth-errors.errors.service=oauth2-proxy@docker
      - traefik.http.middlewares.auth-errors.errors.status=401-403
      - traefik.http.middlewares.auth-errors.errors.query=/oauth2/sign_in

volumes:
  traefik-acme-data:
